### ISSUE TITLE
Regional forecasting lat long boundaries

### ISSUE THREAD

**Issue by mamunir** [microsoft/ClimaX#19]
Hello
Thank you for great work. My query is regarding the calculation of boundaries. In regional forecasting task, there are boundaries given by range of lat/long. Lets say, in north america 

'NorthAmerica': { # 8x14
        'lat_range': (15, 65),
        'lon_range': (220, 300)
    },

and global is obvious

 'Global': { # 32, 64
        'lat_range': (-90, 90),
        'lon_range': (0, 360)
    }

Given the file https://cordex.org/wp-content/uploads/2012/11/CORDEX-domain-description_231015.pdf
with the rectangular legend, calculations are not what mentioned in the code? Can you please breakdown your calculations of ranges, for example north america, so the steps can be mapped to other regions. 
Thanks @rejuvyesh @tung-nd

**Comment by rejuvyesh** [comment]
https://github.com/microsoft/ClimaX/blob/77651530cf1338e772fb00c07bfdcb5c502fa148/src/climax/utils/data_utils.py#L60-L90

describes the current latitude-longitude regions used in CimaX with the mapping to pixel domain defined by:

https://github.com/microsoft/ClimaX/blob/77651530cf1338e772fb00c07bfdcb5c502fa148/src/climax/utils/data_utils.py#L91

I don't think we exactly followed the CORDEX domain descriptions, rather the closest approximation that works with our grid dimensions.

**Comment by mamunir** [comment]
Thank you for your reply. I think I should plot it to validate.

**Comment by rejuvyesh** [comment]
Thank you! Do let us know if there are major discrepancies, so we can fix them!

**Comment by mamunir** [comment]
I just plot the points. it showed that your configuration is somewhat precise subset of the points in CORDEX. Thanks for clarification. Closing issue
