### ISSUE TITLE
The pre-train code has a bug with the number of nodes 

### ISSUE THREAD

**Issue by mahm1846** [microsoft/ClimaX#21]
Hi there,

I am trying to run the pre-training code. However, for the following bug and pre-training can not be done on multiple nodes: 

a) In line 134 of the pre-train config file ('https://github.com/microsoft/ClimaX/blob/main/configs/pretrain_climax.yaml'), only one dataset key is defined, which is 'mpi-esm'.

b) On the other hand, line 177 of the datamodule.py ('https://github.com/microsoft/ClimaX/blob/main/src/climax/pretrain/datamodule.py') asserts that the number of data dictionary key has to match the number of nodes (`assert num_nodes == len(self.dict_data_train.keys())`)

c) Putting, a) and b) together, since you have defined only one dataset key, that means that the pre-training can run on a single node only. 

So, do you have a separate configuration with multiple datasets? 
Or, did you use only a single node with eight GPUs for training (like, a A100 dgx node only)? 
Please, can you clarify?

I look forward to hearing from you.

Best,
Maruf

**Comment by tung-nd** [comment]
Hi,

Thank you for your interest in ClimaX. The current code requires that the number of pretraining datasets matches the number of nodes due to efficiency reasons (reading too many data files belonging to multiple datasets on the same node will create a bottleneck). To get the results in the paper we did pretrain on multiple datasets using multiple nodes, and the config in this repo only serves as an example and users are free to create their new config files for multi-dataset pretraining. As a reference, you can look at this config file: https://github.com/tung-nd/climax_all/blob/main/configs/train_tokenized_vit_multi_cmip6_continuous.yaml

**Comment by mahm1846** [comment]
Thanks very much for the reply.
We are really interested in your model. We have our ERA5 and CMIP6 replicas on disk and already processed ERA5 data for pre-train. We are hoping to preprocess CMIP6, also. However, the multi-node train issue is not solved, yet. 

If two nodes are used, their ranks would be 0 and 1, respectively.
Now, lines 179-182 of `datamodule.py` ('https://github.com/microsoft/ClimaX/blob/main/src/climax/pretrain/datamodule.py') loads only the key index that matches the node rank:
```python
            for idx, k in enumerate(self.dict_data_train.keys()):
                if idx == node_rank:
                    data_train = self.dict_data_train[k]
                    break
```
So, the entire dataset will be loaded in the first node, and the second node will be empty. Thus, it is a "one dataset, one node" rule. 

Even if one uses multiple datasets, one dataset will use only one node, the rest of the nodes will be idle. 
If we want to distribute each dataset to the rest of the cluster, is there a way?

**Comment by tung-nd** [comment]
@mahm1846 did it resolve your issues?

**Comment by mahm1846** [comment]
Hi Tung,

Thanks for your help, I have completed the ERA5 preprocessing. However, I have a question about the CMIP data. Did you use the weatherbench CMIP dataset for pre-training? Or, was it different?

Also, you have snakemake files for data download and processing (https://github.com/tung-nd/climax_all/tree/main/snakemake_configs), which is good.  However, there is no instruction to run the code (https://github.com/tung-nd/climax_all#readme). Please, can you add the steps for data preprocessing? 

I look forward to your reply.
