### ISSUE TITLE
Cannot access pretrained weight

### ISSUE THREAD

**Issue by phamtienkha** [microsoft/ClimaX#23]
Hi there,

I would like to ask if the pretrained weight at [https://climaxrelease.blob.core.windows.net/checkpoints/ClimaX-5.625deg.ckpt](https://climaxrelease.blob.core.windows.net/checkpoints/ClimaX-5.625deg.ckpt) had been opened for public access. If not, could you kindly let me know how to get it?

Many thanks.

**Comment by quantran-13** [comment]
@phamtienkha were you able to download the pretrained weights? I encountered an issue while attempting to access the pretrained model through the provided link. Upon request, I received a response code 409 with the message: "Public access is not permitted on this storage account."

**Comment by phamtienkha** [comment]
> @phamtienkha were you able to download the pretrained weights? I encountered an issue while attempting to access the pretrained model through the provided link. Upon request, I received a response code 409 with the message: "Public access is not permitted on this storage account."

Same for me.

**Comment by rejuvyesh** [comment]
Apologies for the delay. Certain storage policies changed in our Azure bucket and we are working on updated links.

**Comment by tung-nd** [comment]
Hi @phamtienkha and @quantran-13, please use the new checkpoints URL at https://huggingface.co/tungnd/climax/resolve/main/5.625deg.ckpt and https://huggingface.co/tungnd/climax/resolve/main/5.625deg.ckpt
We will update the document soon to reflect these changes

**Comment by rejuvyesh** [comment]
Fixed in #24
