### ISSUE TITLE
Training ClimaX without pre-training

### ISSUE THREAD

**Issue by yogeshverma1998** [microsoft/ClimaX#29]
hi,

Thanks for the repo. Is there a way to train the model without pre-training on ERA5? As when I try the command

`
python -u src/climax/global_forecast/train.py --config configs/global_forecast_climax.yaml --trainer.strategy=ddp --trainer.devices=1 --trainer.max_epochs=50 --data.root_dir=process_data --data.predict_range=24 --data.out_variables=['z_500','t_850','t2m','u10'] --data.batch_size=16 --model.pretrained_path="" --model.lr=5e-7 --model.beta_1="0.9" --model.beta_2="0.99" --model.weight_decay=1e-5
`

It automatically starts with pre-training. Is there a flag somewhere to disable the pre-training and train on ERA5?

Regards,
Yogesh

**Comment by tung-nd** [comment]
If you run this script it should start training on ERA5 without any pretraining

**Comment by tung-nd** [comment]
hi @yogeshverma1998 is this solved? if yes, please close this issue

**Comment by yogeshverma1998** [comment]
Hi, Thanks for the reply. It’s solved now.
