### ISSUE TITLE
Pretrain dataset prepare and Out-of-memory problem

### ISSUE THREAD

**Issue by idevede** [microsoft/ClimaX#34]
Hi there,

Thanks for sharing the great work!

I'm following the https://microsoft.github.io/ClimaX/usage/ to create a pre-training database, and I'm having some problems.

1. using CMIP6 as an example, how much space do I need to store all the files, e.g. "2m_temperature", "10m_u_component_of_wind", # "10m_v_component_of_wind", etc.?
2. Is there a way I can reuse the method ClimateLearn provides for downloading the dataset (https://climatelearn.readthedocs.io/en/latest/user-guide/tasks_and_datasets.html#weatherbench-cmip6-download)
3. I ran the snakemake file and only got 2m_temperature (given the network connection issues and hard disk capacity), then I changed the dict_in_variables: in the config file pretrain_climax.yaml to something like this:

<img width="1008" alt="SmtL weiSe  ereminLSer  eeaokminL secae geekemaial ee bgmal" src="https://github.com/microsoft/ClimaX/assets/9716715/9396c474-ea17-4271-a874-c6dbce535a7d">

After I run

`python src/climax/pretrain/train.py --config configs/pretrain_climax.yaml \

    --trainer.strategy=ddp --trainer.devices=8 \

    --trainer.max_epochs=100 \

    --data.batch_size=16 \

    --model.lr=5e-4 --model.beta_1="0.9" --model.beta_2="0.95" \

    --model.weight_decay=1e-5
`

I encountered two problems
3.1: The input from the neural network alerted me to an image size mismatch, I adjusted the img_size: [32, 64] to img_size: [128, 256] in the yaml file based on this error, the code works, but I don't find any setting that determines the image size in any of the previous operations. How can Iset the image size?

3.2 OOM, even though I have set the batch size to 1, my server still tells me OOM (4*40G, V100), I guess that some variables have been in memory during the pre-training process but not sure how can I deal with that.

Thanks for your time!

**Comment by tung-nd** [comment]
Hi, thanks for your interest in ClimaX.

1. I don't remember the dataset's size, but it should be around a few hundred GBs to ~1TB if you want to store all the variables we used in the paper.
2. Yes you can use climatelearn to download the data. Alternatively, you can also download the data from huggingface https://huggingface.co/datasets/jasonjewik/climate-learn/tree/main/weatherbench/mpi_esm_cmip6
3. You can change the servers determined in the snakemake file based on your location. For example, as I'm based in the US, the most stable servers for me to download are the ones in the US.
3.1. The img_size in the yaml file should match the resolution of your data. To determine the resolution of the CMIP6 data, you should change the resolution (res) information here https://github.com/microsoft/ClimaX/blob/main/snakemake_configs/MPI-ESM/config_2m_temperature.yml and also for other variables
3.2. A batch size of 1 should work with 40GB GPU memory. Can you show me the command you use for training the model, and the config file you use?
