### ISSUE TITLE
How to download the IFS data?

### ISSUE THREAD

**Issue by SauryChen** [microsoft/ClimaX#38]
Hi,
I am trying to download the IFS data from the TIGGE archive, as mentioned in the paper. However, I am not able to connect to the servers listed in Bougeault et al., 2010, such as the [CMA](http://wisportal.cma.gov.cn/tigge/), [ECWMF](http://tigge-portal.ecmwf.int) and [TIGGE](http://tigge.ecmwf.int). Could you please share your ways to download the data?

Thanks a lot!  :)

**Comment by tung-nd** [comment]
We were able to download IFS data from the TIGGE servers, but they may have been down and that's why you cannot connect to them. I believe you can also download IFS predictions from the WeatherBench 2 repo.
