### ISSUE TITLE
How to use trained ClimaX model for predictions?

### ISSUE THREAD

**Issue by CristianMaza** [microsoft/ClimaX#39]
Hello,
I've gone through the ClimaX documentation and understand the data preparation and training process. However, I'm unsure how to use the trained model for nowcasting or short-term weather prediction. Is this possible? If so, could you guide me on how to do this?
Thanks.

**Comment by tung-nd** [comment]
Hi,
Thank you for your interest in ClimaX. Currently, only the pretrained checkpoint of ClimaX is available, not the ones fine-tuned on ERA5 data. You can use this checkpoint to perform forecasting, but the performance might not be ideal. It's best to finetune ClimaX before using it.
