### ISSUE TITLE
If use Docker to build the image as introductions,the name should obey dns rules,and so the name of image must be lowercase?

### ISSUE THREAD

**Issue by Ericc1027** [microsoft/ClimaX#42]
If use Docker to build the image as introductions,the name should obey dns rules,and so the name of image must be lowercase?
After I changed the name of image to upper case,the process can not completed with enviromental errors.

**Comment by rejuvyesh** [comment]
Sorry, I'm not sure what you mean. Can you share the exact command and error?

**Comment by Ericc1027** [comment]
Thanks .PLZ find the errors as follow:
base) mac@macdeMacBook-Pro ClimaX % cd cd docker (base) mac@macdeMacBook-Pro ClimaX % docker build -t ClimaX .
[+] Building 0.0s (0/0)                                                                                           docker:desktop-linux
### _ERROR: invalid tag "ClimaX": repository name must be lowercase_

**Comment by rejuvyesh** [comment]
Ah, okay. Feel free to adjust to all lowercase. I haven't checked these on mac docker. The tag name you use in the docker creation doesn't matter as long as you are consistent!

**Comment by Ericc1027** [comment]
Thanks for your kindness.However,something still went wrong way even I have changed the mirror name to all lowercase:
failed
567.8 
567.8 CondaEnvException: Pip failed
567.8 
------
Dockerfile:39
--------------------
  37 |     ENV PATH=/opt/conda/bin:${PATH}
  38 |     ENV conda update -n base conda
  39 | >>> RUN conda env create -f /tmp/environment.yml
  40 |     
  41 |     SHELL ["conda", "run", "-n", "climaX", "/bin/bash", "-c"]
--------------------
ERROR: failed to solve: process "/bin/sh -c conda env create -f /tmp/environment.yml" did not complete successfully: exit code: 1

SO should I amend the Dockerfile or envirment.yaml files?

**Comment by rejuvyesh** [comment]
This doesn't tell what the exact error is. Likely some package has issues installing? Python packaging is a mess.

**Comment by Ericc1027** [comment]
Thanks a lot。Now I have built an image,and then changed the repository name with all lowercase. When I tried to run the container,the process failed due to mounts denied:
(base) mac@macdeMacBook-Pro ClimaX % docker run --gpus all -it --rm --user $(id -u):$(id -g) \
    -v $(pwd):/code -v /mnt/data:/data --workdir /code -e PYTHONPATH=/code/src \
    ClimaX:latest
docker: invalid reference format: repository name (library/ClimaX) must be lowercase.
See 'docker run --help'.
(base) mac@macdeMacBook-Pro ClimaX % docker run --gpus all -it --rm --user $(id -u):$(id -g) \
    -v $(pwd):/code -v /mnt/data:/data --workdir /code -e PYTHONPATH=/code/src \
    climax:latest
docker: Error response from daemon: Mounts denied: 
The path /mnt/data is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0000] error waiting for container: context canceled 
(base) mac@macdeMacBook-Pro ClimaX % docker run --gpus all -it --rm --user $(id -u):$(id -g) \
    -v $(pwd):/code -v /mnt/data:/data --workdir /code -e PYTHONPATH=/code/src \
    ClimaX:latest
docker: invalid reference format: repository name (library/ClimaX) must be lowercase.
See 'docker run --help'.
(base) mac@macdeMacBook-Pro ClimaX % docker run --gpus all -it --rm --user $(id -u):$(id -g) \
    -v $(pwd):/code -v /mnt/data:/data --workdir /code -e PYTHONPATH=/code/src \
    climax:latest
docker: Error response from daemon: **Mounts denied**: 
The path /mnt/data is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0000] error waiting for container: context canceled

**Comment by rejuvyesh** [comment]
Oh `/mnt/data` is just a random path. You should change it to the path you have your local data stored.
