### ISSUE TITLE
acc and rmse in metrics.py might contain some errors.

### ISSUE THREAD

**Issue by wuangnying** [microsoft/ClimaX#46]
in `val` and `test`, `acc, mse, rmse`calculations are returned together
```
def evaluate(self, ...):
        ...
        return [m(preds, y, transform, out_variables, lat, clim, log_postfix) for m in metrics]
```
but in `metrics.py `
```
def lat_weighted_rmse(pred, y, transform, vars, lat, clim, log_postfix):
    pred = transform(pred)
    y = transform(y)
    error = (pred - y) ** 2
    ...
    return loss_dict
```
```
def lat_weighted_acc(pred, y, transform, vars, lat, clim, log_postfix):
    pred = transform(pred)
    y = transform(y)
    error = (pred - y) ** 2
    ...
    return loss_dict
```
```
def lat_weighted_mse_val(pred, y, transform, vars, lat, clim, log_postfix):
    error = (pred - y) ** 2
    ...
    return loss_dict
```
compared with `mse`, they have one more normalization. 
The vector here should be in a normalized state. If it is normalized more than once, rsme:inf and mse:NaN will be calculated for extremely low std values ​​and negative mean values.
I found this problem when fine-tuning `toa_incident_solar_radiation` data of a region (mean:-0.7650662, std:6.0785015e-07). 
So I want to ask if this is denormalization, but I see in `module.py`
```
def set_denormalization(self, mean, std):
        self.denormalization = transforms.Normalize(mean, std)
```
Why does denormalization still load the same normalization?

**Comment by tung-nd** [comment]
This is the denormalization step, where we transform the variables into their original space. Please see here to see how we computed the mean and std for the denormalization operation https://github.com/microsoft/ClimaX/blob/main/src/climax/global_forecast/train.py#L27

**Comment by wuangnying** [comment]
Thank you for answer，I overlooked the calculations here
