### ISSUE TITLE
How can I measure the performance of a fine-tuned model for a specific region?

### ISSUE THREAD

**Issue by Jeongmingyeong** [microsoft/ClimaX#47]
Thanks for contributing to open source.

I'm trying to use a model to fine-tune the climax for a specific region.
How can I load the checkpoints I've learned from training and measure the performance for a specific region?
I'm reading the climax documentation but I'm not sure where in the code I should change to set the region I want to predict.

For example, I would like to measure the prediction performance for New York in North America. Can this also be obtained using rmse?

Thank you for reading my question!

**Comment by rejuvyesh** [comment]
Current ClimaX might be too low resolution for New York prediction, but you can map the lat-lon to appropriate patch and take the predictions from there.

**Comment by Jeongmingyeong** [comment]
Thank you :)
